apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: 218266829911.dkr.ecr.us-east-1.amazonaws.com/shipping:latest
          ports:
            - containerPort: 8080
