apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-shipping-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-shipping
  template:
    metadata:
      labels:
        app: dev-shipping
    spec:
      containers:
        - name: dev-shipping
          image: 218266829911.dkr.ecr.us-east-1.amazonaws.com/dev-shipping:latest
          ports:
            - containerPort: 8080
